{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "backup-controller.serviceAccountName" . }}
  labels:
    {{- include "backup-controller.labels" . | nindent 4 }}
{{- end }}
