//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClaimRestoreStatus) DeepCopyInto(out *ClaimRestoreStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClaimRestoreStatus.
func (in *ClaimRestoreStatus) DeepCopy() *ClaimRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(ClaimRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeRestore) DeepCopyInto(out *VolumeRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeRestore.
func (in *VolumeRestore) DeepCopy() *VolumeRestore {
	if in == nil {
		return nil
	}
	out := new(VolumeRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VolumeRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeRestoreList) DeepCopyInto(out *VolumeRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VolumeRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeRestoreList.
func (in *VolumeRestoreList) DeepCopy() *VolumeRestoreList {
	if in == nil {
		return nil
	}
	out := new(VolumeRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VolumeRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeRestoreSpec) DeepCopyInto(out *VolumeRestoreSpec) {
	*out = *in
	if in.RestoreAsOf != nil {
		in, out := &in.RestoreAsOf, &out.RestoreAsOf
		*out = new(string)
		**out = **in
	}
	if in.MoverPodLabels != nil {
		in, out := &in.MoverPodLabels, &out.MoverPodLabels
		*out = make(map[string]MoverPodLabelValue, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MoverSecurityContext != nil {
		in, out := &in.MoverSecurityContext, &out.MoverSecurityContext
		*out = new(v1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeRestoreSpec.
func (in *VolumeRestoreSpec) DeepCopy() *VolumeRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(VolumeRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeRestoreStatus) DeepCopyInto(out *VolumeRestoreStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Claims != nil {
		in, out := &in.Claims, &out.Claims
		*out = make([]ClaimRestoreStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeRestoreStatus.
func (in *VolumeRestoreStatus) DeepCopy() *VolumeRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(VolumeRestoreStatus)
	in.DeepCopyInto(out)
	return out
}
