//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupItem) DeepCopyInto(out *BackupItem) {
	*out = *in
	if in.SnapshotTime != nil {
		in, out := &in.SnapshotTime, &out.SnapshotTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupItem.
func (in *BackupItem) DeepCopy() *BackupItem {
	if in == nil {
		return nil
	}
	out := new(BackupItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRun) DeepCopyInto(out *BackupRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRun.
func (in *BackupRun) DeepCopy() *BackupRun {
	if in == nil {
		return nil
	}
	out := new(BackupRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRunList) DeepCopyInto(out *BackupRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BackupRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRunList.
func (in *BackupRunList) DeepCopy() *BackupRunList {
	if in == nil {
		return nil
	}
	out := new(BackupRunList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupRunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRunSpec) DeepCopyInto(out *BackupRunSpec) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.TTLSecondsAfterFinished != nil {
		in, out := &in.TTLSecondsAfterFinished, &out.TTLSecondsAfterFinished
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRunSpec.
func (in *BackupRunSpec) DeepCopy() *BackupRunSpec {
	if in == nil {
		return nil
	}
	out := new(BackupRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRunStatus) DeepCopyInto(out *BackupRunStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.QuiescedAt != nil {
		in, out := &in.QuiescedAt, &out.QuiescedAt
		*out = (*in).DeepCopy()
	}
	if in.RestartedAt != nil {
		in, out := &in.RestartedAt, &out.RestartedAt
		*out = (*in).DeepCopy()
	}
	if in.Quiesced != nil {
		in, out := &in.Quiesced, &out.Quiesced
		*out = make([]QuiescedWorkload, len(*in))
		copy(*out, *in)
	}
	if in.SuspendedKustomizations != nil {
		in, out := &in.SuspendedKustomizations, &out.SuspendedKustomizations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BackupItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRunStatus.
func (in *BackupRunStatus) DeepCopy() *BackupRunStatus {
	if in == nil {
		return nil
	}
	out := new(BackupRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClaimRestoreStatus) DeepCopyInto(out *ClaimRestoreStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClaimRestoreStatus.
func (in *ClaimRestoreStatus) DeepCopy() *ClaimRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(ClaimRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuiescedWorkload) DeepCopyInto(out *QuiescedWorkload) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuiescedWorkload.
func (in *QuiescedWorkload) DeepCopy() *QuiescedWorkload {
	if in == nil {
		return nil
	}
	out := new(QuiescedWorkload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreItem) DeepCopyInto(out *RestoreItem) {
	*out = *in
	if in.SnapshotTime != nil {
		in, out := &in.SnapshotTime, &out.SnapshotTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreItem.
func (in *RestoreItem) DeepCopy() *RestoreItem {
	if in == nil {
		return nil
	}
	out := new(RestoreItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreRun) DeepCopyInto(out *RestoreRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreRun.
func (in *RestoreRun) DeepCopy() *RestoreRun {
	if in == nil {
		return nil
	}
	out := new(RestoreRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RestoreRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreRunList) DeepCopyInto(out *RestoreRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RestoreRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreRunList.
func (in *RestoreRunList) DeepCopy() *RestoreRunList {
	if in == nil {
		return nil
	}
	out := new(RestoreRunList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RestoreRunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreRunSpec) DeepCopyInto(out *RestoreRunSpec) {
	*out = *in
	if in.IntoSize != nil {
		in, out := &in.IntoSize, &out.IntoSize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.RestoreAsOf != nil {
		in, out := &in.RestoreAsOf, &out.RestoreAsOf
		*out = new(string)
		**out = **in
	}
	if in.Previous != nil {
		in, out := &in.Previous, &out.Previous
		*out = new(int32)
		**out = **in
	}
	if in.Quiesce != nil {
		in, out := &in.Quiesce, &out.Quiesce
		*out = make([]WorkloadRef, len(*in))
		copy(*out, *in)
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MoverSecurityContext != nil {
		in, out := &in.MoverSecurityContext, &out.MoverSecurityContext
		*out = new(corev1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.TTLSecondsAfterFinished != nil {
		in, out := &in.TTLSecondsAfterFinished, &out.TTLSecondsAfterFinished
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreRunSpec.
func (in *RestoreRunSpec) DeepCopy() *RestoreRunSpec {
	if in == nil {
		return nil
	}
	out := new(RestoreRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreRunStatus) DeepCopyInto(out *RestoreRunStatus) {
	*out = *in
	if in.SyncedTo != nil {
		in, out := &in.SyncedTo, &out.SyncedTo
		*out = (*in).DeepCopy()
	}
	if in.QuiescedAt != nil {
		in, out := &in.QuiescedAt, &out.QuiescedAt
		*out = (*in).DeepCopy()
	}
	if in.RestartedAt != nil {
		in, out := &in.RestartedAt, &out.RestartedAt
		*out = (*in).DeepCopy()
	}
	if in.Quiesced != nil {
		in, out := &in.Quiesced, &out.Quiesced
		*out = make([]QuiescedWorkload, len(*in))
		copy(*out, *in)
	}
	if in.SuspendedKustomizations != nil {
		in, out := &in.SuspendedKustomizations, &out.SuspendedKustomizations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RestoreItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreRunStatus.
func (in *RestoreRunStatus) DeepCopy() *RestoreRunStatus {
	if in == nil {
		return nil
	}
	out := new(RestoreRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeRestore) DeepCopyInto(out *VolumeRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeRestore.
func (in *VolumeRestore) DeepCopy() *VolumeRestore {
	if in == nil {
		return nil
	}
	out := new(VolumeRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VolumeRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeRestoreList) DeepCopyInto(out *VolumeRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VolumeRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeRestoreList.
func (in *VolumeRestoreList) DeepCopy() *VolumeRestoreList {
	if in == nil {
		return nil
	}
	out := new(VolumeRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VolumeRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeRestoreSpec) DeepCopyInto(out *VolumeRestoreSpec) {
	*out = *in
	if in.RestoreAsOf != nil {
		in, out := &in.RestoreAsOf, &out.RestoreAsOf
		*out = new(string)
		**out = **in
	}
	if in.CacheStorageClassName != nil {
		in, out := &in.CacheStorageClassName, &out.CacheStorageClassName
		*out = new(string)
		**out = **in
	}
	if in.CacheCapacity != nil {
		in, out := &in.CacheCapacity, &out.CacheCapacity
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MoverPodLabels != nil {
		in, out := &in.MoverPodLabels, &out.MoverPodLabels
		*out = make(map[string]MoverPodLabelValue, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MoverSecurityContext != nil {
		in, out := &in.MoverSecurityContext, &out.MoverSecurityContext
		*out = new(corev1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeRestoreSpec.
func (in *VolumeRestoreSpec) DeepCopy() *VolumeRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(VolumeRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeRestoreStatus) DeepCopyInto(out *VolumeRestoreStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Claims != nil {
		in, out := &in.Claims, &out.Claims
		*out = make([]ClaimRestoreStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeRestoreStatus.
func (in *VolumeRestoreStatus) DeepCopy() *VolumeRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(VolumeRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadRef) DeepCopyInto(out *WorkloadRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadRef.
func (in *WorkloadRef) DeepCopy() *WorkloadRef {
	if in == nil {
		return nil
	}
	out := new(WorkloadRef)
	in.DeepCopyInto(out)
	return out
}
